// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://otonwcoxabgnmdnflfpj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im90b253Y294YWJnbm1kbmZsZnBqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNjI0NzQsImV4cCI6MjA2OTkzODQ3NH0.Dq_KJucjPcQybYiodiq-lV9NQCRc_5oMzUdx8UFoSEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});